# Generated by Django 5.2.2 on 2025-06-05 08:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='Untitled Project', max_length=255)),
                ('customer_id', models.IntegerField(default=0)),
                ('project_description', models.TextField(default='No description provided.')),
                ('project_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_actual_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_actual_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('project_manager_id', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(default=0)),
                ('customer_id', models.IntegerField(default=0)),
                ('project_manager_id', models.IntegerField(default=0)),
                ('sprint_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('sprint_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('sprint_description', models.TextField(default='No description provided.')),
                ('estimated_hours', models.IntegerField(default=0)),
                ('total_items', models.IntegerField(default=0)),
                ('total_completed', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
